# Changes here will be overwritten by Copier
_commit: 57d586c
_src_path: https://github.com/nialov/nialov-py-template.git
classifier: "Topic :: Scientific/Engineering :: GIS"
description: Kapalo data extraction and processing
email: nikolasovaskainen@gmail.com
full_name: Nikolas Ovaskainen
github_account: nialov
keywords: data analysis spatial geology
package: kapalo_py
year: 2021
