# Changes here will be overwritten by Copier
_commit: f7ca2f8
_src_path: https://github.com/nialov/nialov-py-template.git
classifier: 'Topic :: Scientific/Engineering :: GIS'
description: Kapalo data extraction and processing
email: nikolasovaskainen@gmail.com
full_name: Nikolas Ovaskainen
github_account: nialov
keyword: data
package: kapalo_py
year: 2021
